fix_action.py

not learning at all.

ok, mdn_error was wrong.

fix_and_run?